<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Placeholder content for the category system. One full 10-question
        // round per category for now — expand these later.
        $this->seedCategory('Food', [
            ['What fruit is known as the "king of fruits" in Southeast Asia?', 'Mango', 'Durian', 'Rambutan', 'Lychee', 'B'],
            ['Which spice is derived from the crocus flower and is the most expensive by weight?', 'Saffron', 'Cinnamon', 'Nutmeg', 'Cardamom', 'A'],
            ['What is the main ingredient in traditional hummus?', 'Chickpeas', 'Lentils', 'Black beans', 'Kidney beans', 'A'],
            ['Which country is credited with inventing pizza in its modern form?', 'France', 'Greece', 'Italy', 'Spain', 'C'],
            ['Which of these is technically a fruit, not a vegetable?', 'Tomato', 'Carrot', 'Potato', 'Broccoli', 'A'],
            ['What is the primary flavor in traditional pesto sauce?', 'Basil', 'Parsley', 'Cilantro', 'Mint', 'A'],
            ['Sushi originated in which country?', 'China', 'Japan', 'Korea', 'Thailand', 'B'],
            ['What is the most consumed beverage in the world after water?', 'Coffee', 'Tea', 'Beer', 'Orange juice', 'B'],
            ['Which cheese is traditionally used on a Margherita pizza?', 'Cheddar', 'Mozzarella', 'Parmesan', 'Gouda', 'B'],
            ['What grain is the main ingredient in traditional Japanese sake?', 'Wheat', 'Barley', 'Rice', 'Corn', 'C'],
            ['What is the main ingredient in guacamole?', 'Tomato', 'Avocado', 'Onion', 'Lime', 'B'],
            ['Tofu is made primarily from which food?', 'Rice', 'Corn', 'Soybeans', 'Peanuts', 'C'],
            ['Which nut is the primary ingredient in marzipan?', 'Walnuts', 'Cashews', 'Peanuts', 'Almonds', 'D'],
            ['Baklava is made using which type of pastry dough?', 'Puff pastry', 'Phyllo dough', 'Shortcrust', 'Choux pastry', 'B'],
            ['What is the base of traditional French ratatouille?', 'Rice', 'Beans', 'Mixed vegetables', 'Potatoes', 'C'],
            ['Which spice gives traditional curry its yellow color?', 'Paprika', 'Cumin', 'Coriander', 'Turmeric', 'D'],
            ['Miso paste is traditionally made by fermenting which food?', 'Seaweed', 'Soybeans', 'Rice', 'Fish', 'B'],
            ['Which pepper is widely cited as the world\'s hottest?', 'Habanero', 'Scotch Bonnet', 'Carolina Reaper', 'Ghost Pepper', 'C'],
            ['Which country produces the most coffee in the world?', 'Colombia', 'Vietnam', 'Ethiopia', 'Brazil', 'D'],
            ['What are the main ingredients in traditional falafel?', 'Lentils', 'Chickpeas or fava beans', 'Black beans', 'Split peas', 'B'],
            ['What is another common name for a scallion?', 'Shallot', 'Leek', 'Green onion', 'Chive', 'C'],
            ['Tzatziki sauce is primarily made from which dairy product?', 'Sour cream', 'Cream cheese', 'Mayonnaise', 'Yogurt', 'D'],
            ['The sandwich is said to be named after which English nobleman?', 'Duke of York', 'Earl of Sandwich', 'Lord Grey', 'Earl of Essex', 'B'],
            ['Traditional Italian risotto is made with which type of rice?', 'Basmati', 'Jasmine', 'Arborio', 'Long-grain', 'C'],
            ['Balsamic vinegar is made by fermenting which fruit?', 'Apples', 'Pears', 'Plums', 'Grapes', 'D'],
            ['What gives classic French onion soup its signature flavor base?', 'Tomatoes', 'Caramelized onions', 'Mushrooms', 'Carrots', 'B'],
            ['Paprika is made by grinding and drying which vegetable?', 'Tomatoes', 'Carrots', 'Beets', 'Peppers', 'D'],
            ['Paella is a traditional dish from which country?', 'Portugal', 'Italy', 'Mexico', 'Spain', 'D'],
            ['What is the main ingredient in traditional Indian dal?', 'Chickpeas', 'Rice', 'Lentils', 'Wheat', 'C'],
            ['Kimchi, a Korean staple, is traditionally made by fermenting which vegetable?', 'Carrots', 'Radishes', 'Cucumbers', 'Napa cabbage', 'D'],
        ]);

        $this->seedCategory('Animals', [
            ['What is the largest land animal?', 'African elephant', 'White rhinoceros', 'Giraffe', 'Hippopotamus', 'A'],
            ['Which animal is known to sleep for up to 20 hours a day?', 'Koala', 'Sloth', 'Lion', 'Panda', 'A'],
            ['What is a baby kangaroo called?', 'Cub', 'Joey', 'Kid', 'Pup', 'B'],
            ['Which bird is known for its ability to mimic human speech?', 'Eagle', 'Parrot', 'Owl', 'Sparrow', 'B'],
            ['What is the fastest land animal?', 'Lion', 'Cheetah', 'Pronghorn', 'Greyhound', 'B'],
            ['How many legs does a spider have?', '6', '8', '10', '12', 'B'],
            ['Which mammal is the only one capable of true flight?', 'Flying squirrel', 'Bat', 'Sugar glider', 'Colugo', 'B'],
            ['What is the largest species of shark?', 'Great White Shark', 'Whale Shark', 'Tiger Shark', 'Hammerhead Shark', 'B'],
            ['Which big cat is known for having a mane in males?', 'Tiger', 'Lion', 'Leopard', 'Jaguar', 'B'],
            ['What do you call a group of lions?', 'Pack', 'Pride', 'Herd', 'Flock', 'B'],
            ['What is a group of crows called?', 'A flock', 'A murder', 'A parliament', 'A gaggle', 'B'],
            ['Which big cat is the largest in the world?', 'Tiger', 'Lion', 'Jaguar', 'Leopard', 'A'],
            ['What is the tallest animal in the world?', 'Giraffe', 'Elephant', 'Ostrich', 'Camel', 'A'],
            ['Which animal is known for changing color to camouflage itself?', 'Iguana', 'Chameleon', 'Gecko', 'Frog', 'B'],
            ['Which animal is considered one of the closest living relatives to humans?', 'Gorilla', 'Chimpanzee', 'Orangutan', 'Bonobo', 'B'],
            ['Which animal has black and white stripes unique to each individual?', 'Zebra', 'Panda', 'Skunk', 'Tapir', 'A'],
            ['What is a baby cow called?', 'Calf', 'Foal', 'Kid', 'Cub', 'A'],
            ['Which reptile is known for shedding its tail to escape predators?', 'Snake', 'Lizard', 'Turtle', 'Crocodile', 'B'],
            ['What is the largest species of bear?', 'Polar bear', 'Kodiak bear', 'Grizzly bear', 'Black bear', 'A'],
            ['Which insect is known for its ability to lift many times its own body weight?', 'Beetle', 'Ant', 'Bee', 'Grasshopper', 'B'],
            ['What is a group of wolves called?', 'Pack', 'Herd', 'Pod', 'Colony', 'A'],
            ['Which animal is the largest rodent in the world?', 'Beaver', 'Capybara', 'Porcupine', 'Groundhog', 'B'],
            ['About how many hearts does an earthworm have?', '1', '3', '5', '7', 'C'],
            ['Which flightless bird is the fastest runner among birds?', 'Penguin', 'Ostrich', 'Kiwi', 'Emu', 'B'],
            ['Giraffes are found in the wild on which continent?', 'Asia', 'South America', 'Africa', 'Australia', 'C'],
            ['Which of these animals is known for sleeping while standing up?', 'Horse', 'Cow', 'Elephant', 'All of the above', 'D'],
            ['What is a baby goat called?', 'Kid', 'Foal', 'Fawn', 'Cub', 'A'],
            ['Which venomous snake is known for its ability to "spit" venom at threats?', 'Cobra', 'Rattlesnake', 'Viper', 'Mamba', 'A'],
            ['What is considered the fastest fish in the ocean?', 'Sailfish', 'Marlin', 'Tuna', 'Swordfish', 'A'],
            ['Which mammal is known for laying eggs instead of giving live birth?', 'Platypus', 'Kangaroo', 'Koala', 'Armadillo', 'A'],
        ]);

        $this->seedCategory('Movies', [
            ['Which movie won the first-ever Academy Award for Best Picture (1929)?', 'Wings', 'Metropolis', 'Sunrise', 'The Jazz Singer', 'A'],
            ['Who directed the movie "Jaws" (1975)?', 'George Lucas', 'Steven Spielberg', 'Martin Scorsese', 'Francis Ford Coppola', 'B'],
            ['Which studio produced the "Toy Story" franchise?', 'DreamWorks', 'Illumination', 'Pixar', 'Blue Sky Studios', 'C'],
            ['In "The Wizard of Oz," what color are Dorothy\'s iconic shoes?', 'Silver', 'Red', 'Gold', 'Blue', 'B'],
            ['Which actor played Iron Man in the Marvel Cinematic Universe?', 'Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo', 'C'],
            ['Which film franchise features a wizarding school called Hogwarts?', 'Lord of the Rings', 'Harry Potter', 'Narnia', 'Percy Jackson', 'B'],
            ['Which 1994 film features the line "Life is like a box of chocolates"?', 'Forrest Gump', 'Pulp Fiction', 'The Shawshank Redemption', 'Home Alone', 'A'],
            ['Who composed the iconic score for "Star Wars"?', 'Hans Zimmer', 'John Williams', 'James Horner', 'Danny Elfman', 'B'],
            ['Which animated film features the song "Let It Go"?', 'Moana', 'Frozen', 'Tangled', 'Encanto', 'B'],
            ['What is the name of the fictional African country in "Black Panther"?', 'Zamunda', 'Wakanda', 'Genovia', 'Sokovia', 'B'],
            ['Which movie franchise features a shark terrorizing the beach town of Amity Island?', 'Deep Blue Sea', 'Jaws', 'The Meg', 'Open Water', 'B'],
            ['Who directed "Pulp Fiction" (1994)?', 'Martin Scorsese', 'Quentin Tarantino', 'David Fincher', 'Christopher Nolan', 'B'],
            ['Which film won the Academy Award for Best Picture in 2020, centered on a Korean family?', 'Roma', '1917', 'Parasite', 'Joker', 'C'],
            ['In "Star Wars," what is the name of Luke Skywalker\'s home planet?', 'Naboo', 'Tatooine', 'Hoth', 'Endor', 'B'],
            ['Which actress played Hermione Granger in the "Harry Potter" films?', 'Bonnie Wright', 'Emma Watson', 'Evanna Lynch', 'Katie Leung', 'B'],
            ['Which Pixar film follows a clownfish searching for his missing son?', 'Shark Tale', 'Finding Nemo', 'The Little Mermaid', 'Moana', 'B'],
            ['Who played the Joker in "The Dark Knight" (2008)?', 'Jared Leto', 'Joaquin Phoenix', 'Heath Ledger', 'Jack Nicholson', 'C'],
            ['Which 1997 film stars Leonardo DiCaprio and Kate Winslet aboard a doomed ocean liner?', 'Titanic', 'The Perfect Storm', 'Poseidon', 'The Aviator', 'A'],
            ['Which studio created the "Shrek" franchise?', 'Pixar', 'DreamWorks', 'Illumination', 'Blue Sky Studios', 'B'],
            ['In "The Lion King," what is the name of Simba\'s father?', 'Scar', 'Rafiki', 'Mufasa', 'Zazu', 'C'],
            ['Which director is known for films like "Inception" and "Interstellar"?', 'Christopher Nolan', 'Ridley Scott', 'James Cameron', 'Denis Villeneuve', 'A'],
            ['Which of these films is often cited as the highest-grossing movie of all time (unadjusted for inflation)?', 'Avatar', 'Avengers: Endgame', 'Titanic', 'Star Wars: The Force Awakens', 'A'],
            ['Which actor voices Woody in the "Toy Story" franchise?', 'Tim Allen', 'Tom Hanks', 'John Ratzenberger', 'Don Rickles', 'B'],
            ['In "Back to the Future," what type of car is the time machine built from?', 'A DeLorean', 'A Ford Mustang', 'A Chevrolet', 'A Volkswagen Beetle', 'A'],
            ['Which movie features the fictional restaurant "Krusty Krab"?', 'Finding Nemo', 'The SpongeBob SquarePants Movie', 'Shark Tale', 'Moana', 'B'],
            ['Who directed "The Godfather" (1972)?', 'Martin Scorsese', 'Francis Ford Coppola', 'Sidney Lumet', 'Sergio Leone', 'B'],
            ['Which film series follows a boy wizard who battles the Dark Lord Voldemort?', 'Narnia', 'Percy Jackson', 'Harry Potter', 'His Dark Materials', 'C'],
            ['What is the name of the toy cowboy voiced by Tom Hanks in "Toy Story"?', 'Buzz', 'Woody', 'Rex', 'Slinky', 'B'],
            ['Which animated Disney film follows a Chinese girl who takes her father\'s place in the army?', 'Pocahontas', 'Mulan', 'Aladdin', 'Moana', 'B'],
            ['Which movie features the line "May the Force be with you"?', 'Star Trek', 'Star Wars', 'Guardians of the Galaxy', 'Dune', 'B'],
        ]);

        $this->seedCategory('Computers', [
            ['What does "CPU" stand for?', 'Central Process Unit', 'Central Processing Unit', 'Computer Personal Unit', 'Central Processor Utility', 'B'],
            ['Who is considered the co-founder of Apple alongside Steve Jobs?', 'Bill Gates', 'Steve Wozniak', 'Elon Musk', 'Larry Page', 'B'],
            ['What does "HTML" stand for?', 'HyperText Markup Language', 'HighText Machine Language', 'HyperTransfer Markup Language', 'Home Tool Markup Language', 'A'],
            ['Which company developed the Windows operating system?', 'Apple', 'IBM', 'Microsoft', 'Google', 'C'],
            ['What does "RAM" stand for?', 'Random Access Memory', 'Read Access Memory', 'Rapid Access Module', 'Random Allocation Memory', 'A'],
            ['The binary number system is based on which base?', 'Base 8', 'Base 10', 'Base 2', 'Base 16', 'C'],
            ['Which language powers Laravel, the web framework this game is built with?', 'Python', 'Ruby', 'PHP', 'JavaScript', 'C'],
            ['What does "URL" stand for?', 'Uniform Resource Locator', 'Universal Reference Link', 'Uniform Retrieval Location', 'Universal Resource Locator', 'A'],
            ['Which company created the JavaScript framework React?', 'Google', 'Microsoft', 'Meta (Facebook)', 'Amazon', 'C'],
            ['What does "SQL" stand for?', 'Structured Query Language', 'Sequential Query Logic', 'Simple Query Language', 'Structured Question Language', 'A'],
            ['What does "GPU" stand for?', 'General Processing Unit', 'Graphics Processing Unit', 'Global Processing Unit', 'Graphic Program Unit', 'B'],
            ['Who is considered the "father of the World Wide Web"?', 'Bill Gates', 'Tim Berners-Lee', 'Steve Jobs', 'Vint Cerf', 'B'],
            ['What does "USB" stand for?', 'Universal Serial Bus', 'United Serial Bus', 'Universal System Bus', 'Unified Serial Bus', 'A'],
            ['Which company developed the Android operating system?', 'Apple', 'Microsoft', 'Google', 'Samsung', 'C'],
            ['What does "AI" stand for in technology?', 'Automated Intelligence', 'Artificial Intelligence', 'Advanced Interface', 'Applied Informatics', 'B'],
            ['Which programming language is especially popular in data science and machine learning?', 'Java', 'Python', 'Ruby', 'C++', 'B'],
            ['Which wireless technology lets nearby devices connect and exchange data without cables, named after a Danish king?', 'Wi-Fi', 'NFC', 'Bluetooth', 'Ethernet', 'C'],
            ['Which company created the iPhone?', 'Samsung', 'Google', 'Apple', 'Microsoft', 'C'],
            ['What was the name of one of the first widely-used web browsers, released in 1993?', 'Internet Explorer', 'Netscape Navigator', 'Mosaic', 'Firefox', 'C'],
            ['What does "PDF" stand for?', 'Portable Document Format', 'Personal Document File', 'Printed Document Format', 'Public Document File', 'A'],
            ['What was Facebook originally named when it launched in 2004?', 'TheFacebook', 'MyFace', 'Facebook Inc.', 'Meta', 'A'],
            ['How many bits make up one byte?', '4', '8', '16', '2', 'B'],
            ['Which two people co-founded Google?', 'Larry Page and Sergey Brin', 'Bill Gates and Paul Allen', 'Steve Jobs and Steve Wozniak', 'Jeff Bezos and Elon Musk', 'A'],
            ['What does "VPN" stand for?', 'Virtual Private Network', 'Verified Public Network', 'Virtual Public Node', 'Variable Private Network', 'A'],
            ['Which of these is a widely used version control system among software developers?', 'Git', 'Docker', 'Kubernetes', 'Jenkins', 'A'],
            ['What does "OS" stand for in computing?', 'Online System', 'Operating System', 'Output System', 'Operational Software', 'B'],
            ['Which tech company\'s logo is a partially eaten fruit?', 'Amazon', 'Apple', 'Samsung', 'Dell', 'B'],
            ['Which browser did Microsoft release to replace Internet Explorer?', 'Chrome', 'Edge', 'Safari', 'Opera', 'B'],
            ['What does "IP" stand for in "IP address"?', 'Internet Protocol', 'Internal Protocol', 'Internet Provider', 'Information Protocol', 'A'],
            ['What does "HTTP" stand for?', 'HyperText Transfer Protocol', 'HighText Transfer Process', 'HyperText Transmission Protocol', 'Home Transfer Text Protocol', 'A'],
        ]);

        $this->seedCategory('Ocean', [
            ['What is the largest ocean on Earth?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 'D'],
            ['What is the deepest known point in Earth\'s oceans?', 'Mariana Trench', 'Puerto Rico Trench', 'Java Trench', 'Tonga Trench', 'A'],
            ['What is the largest animal to have ever lived on Earth?', 'Blue whale', 'Sperm whale', 'Whale shark', 'Giant squid', 'A'],
            ['Which ocean current is known for its warm waters flowing from the Gulf of Mexico?', 'Humboldt Current', 'Gulf Stream', 'Kuroshio Current', 'Benguela Current', 'B'],
            ['Roughly what percentage of Earth\'s surface is covered by oceans?', '50%', '60%', '71%', '85%', 'C'],
            ['What is a group of fish called?', 'Pod', 'School', 'Herd', 'Pack', 'B'],
            ['Which sea creature has three hearts?', 'Octopus', 'Squid', 'Jellyfish', 'Starfish', 'A'],
            ['What is coral primarily made of?', 'Plant matter', 'Rock', 'Tiny living animals (polyps)', 'Algae only', 'C'],
            ['Which sea is known for its unusually high salinity due to high evaporation and low freshwater inflow?', 'Baltic Sea', 'Red Sea', 'Black Sea', 'Caspian Sea', 'B'],
            ['What is the term for the tidal area where a river meets the sea?', 'Delta', 'Estuary', 'Isthmus', 'Fjord', 'B'],
            ['What process do phytoplankton use to convert sunlight into energy?', 'Photosynthesis', 'Respiration', 'Osmosis', 'Fermentation', 'A'],
            ['What is the deep ocean zone called where no sunlight penetrates at all?', 'Sunlight zone', 'Twilight zone', 'Midnight zone', 'Abyssal zone', 'C'],
            ['Which of these is the saltiest large body of water on Earth?', 'Dead Sea', 'Red Sea', 'Mediterranean Sea', 'Caspian Sea', 'A'],
            ['What is a baby seal called?', 'Pup', 'Calf', 'Cub', 'Kit', 'A'],
            ['Which ocean is the smallest by area?', 'Indian', 'Atlantic', 'Arctic', 'Southern', 'C'],
            ['What is the name for an underwater mountain range that forms where tectonic plates spread apart?', 'Mid-ocean ridge', 'Continental shelf', 'Abyssal plain', 'Trench', 'A'],
            ['Which sea creature is considered one of the most venomous animals in the world?', 'Box jellyfish', 'Sea urchin', 'Stonefish', 'Lionfish', 'A'],
            ['What term describes animals that live on or near the ocean floor?', 'Pelagic', 'Benthic', 'Neritic', 'Planktonic', 'B'],
            ['Which marine mammal is nicknamed the "canary of the sea" for its varied vocalizations?', 'Orca', 'Beluga whale', 'Dolphin', 'Narwhal', 'B'],
            ['Which is the largest species of sea turtle?', 'Green sea turtle', 'Loggerhead turtle', 'Leatherback turtle', 'Hawksbill turtle', 'C'],
            ['Which fish is known for inflating its body to deter predators?', 'Pufferfish', 'Clownfish', 'Angelfish', 'Lionfish', 'A'],
            ['What is a young eel called?', 'Elver', 'Fry', 'Fingerling', 'Smolt', 'A'],
            ['Which ocean zone is closest to the surface and receives the most sunlight?', 'Twilight zone', 'Sunlight zone', 'Midnight zone', 'Abyssal zone', 'B'],
            ['What is the longest mountain range in the world, located mostly underwater?', 'Andes', 'Rockies', 'Mid-Atlantic Ridge', 'Himalayas', 'C'],
            ['What do you call a group of dolphins?', 'Pod', 'School', 'Herd', 'Raft', 'A'],
            ['Which ocean borders the eastern coast of the United States?', 'Pacific', 'Atlantic', 'Indian', 'Arctic', 'B'],
            ['What is it called when cold, nutrient-rich water rises to the ocean surface?', 'Upwelling', 'Downwelling', 'Convection', 'Tidal surge', 'A'],
            ['Which sea creature has no brain and is made up of roughly 95% water?', 'Jellyfish', 'Octopus', 'Squid', 'Starfish', 'A'],
            ['What is the largest coral reef system in the world?', 'Belize Barrier Reef', 'Great Barrier Reef', 'Red Sea Coral Reef', 'Florida Reef', 'B'],
            ['Which defense mechanism do octopuses use to escape predators?', 'Releasing ink', 'Growing spikes', 'Changing size', 'Producing venom spray', 'A'],
        ]);

        $this->seedCategory('Music', [
            ['How many strings does a standard guitar have?', '4', '5', '6', '7', 'C'],
            ['Which composer wrote the "Ninth Symphony," completed while he was deaf?', 'Mozart', 'Bach', 'Beethoven', 'Chopin', 'C'],
            ['What does "BPM" stand for in music?', 'Beats Per Minute', 'Bars Per Measure', 'Bass Per Melody', 'Beats Per Measure', 'A'],
            ['Which band released the album "Abbey Road"?', 'The Rolling Stones', 'The Beatles', 'Led Zeppelin', 'Pink Floyd', 'B'],
            ['What is the term for singing without instrumental accompaniment?', 'Acoustic', 'A cappella', 'Falsetto', 'Unplugged', 'B'],
            ['Which instrument is Yo-Yo Ma famous for playing?', 'Violin', 'Piano', 'Cello', 'Flute', 'C'],
            ['How many keys are on a standard piano?', '76', '88', '92', '100', 'B'],
            ['Which genre of music is most directly credited to originating in New Orleans?', 'Reggae', 'Jazz', 'Country', 'Blues', 'B'],
            ['Who is known as the "King of Pop"?', 'Elvis Presley', 'Prince', 'Michael Jackson', 'Freddie Mercury', 'C'],
            ['What clef is typically used for bass notes?', 'Treble clef', 'Bass clef', 'Alto clef', 'Tenor clef', 'B'],
            ['Which artist is widely known as the "Queen of Pop"?', 'Whitney Houston', 'Madonna', 'Mariah Carey', 'Celine Dion', 'B'],
            ['How many members were in the classic lineup of the band ABBA?', '2', '3', '4', '5', 'C'],
            ['Which instrument is famously played by musician Elton John?', 'Guitar', 'Piano', 'Drums', 'Saxophone', 'B'],
            ['Which music genre originated in Jamaica in the late 1960s?', 'Ska', 'Reggae', 'Calypso', 'Soca', 'B'],
            ['Who composed "The Four Seasons," a famous set of violin concertos?', 'Bach', 'Mozart', 'Vivaldi', 'Handel', 'C'],
            ['Which band is known for the song "Bohemian Rhapsody"?', 'The Who', 'Queen', 'Led Zeppelin', 'Pink Floyd', 'B'],
            ['What does "DJ" stand for?', 'Disc Jockey', 'Digital Jockey', 'Dance Judge', 'Disc Journey', 'A'],
            ['Which instrument family does the trumpet belong to?', 'Woodwind', 'Brass', 'Percussion', 'String', 'B'],
            ['Who is known as the "Godfather of Soul"?', 'Ray Charles', 'James Brown', 'Otis Redding', 'Marvin Gaye', 'B'],
            ['Which music streaming platform, launched in 2008, helped popularize on-demand streaming?', 'Spotify', 'Apple Music', 'Pandora', 'SoundCloud', 'A'],
            ['What is the term for a piece of music featuring a soloist accompanied by an orchestra?', 'Symphony', 'Concerto', 'Sonata', 'Overture', 'B'],
            ['Which pop star released the album "Thriller" in 1982?', 'Prince', 'Michael Jackson', 'George Michael', 'Lionel Richie', 'B'],
            ['Which country music legend is known as the "Man in Black"?', 'Willie Nelson', 'Johnny Cash', 'Kris Kristofferson', 'Merle Haggard', 'B'],
            ['What is the highest female singing voice classification?', 'Alto', 'Mezzo-soprano', 'Soprano', 'Contralto', 'C'],
            ['Which band released the album "The Dark Side of the Moon"?', 'The Beatles', 'Pink Floyd', 'Led Zeppelin', 'The Rolling Stones', 'B'],
            ['What is a group of singers performing together, usually without instruments, called?', 'Orchestra', 'Choir', 'Ensemble', 'Band', 'B'],
            ['Which artist is famously associated with the song "Purple Rain"?', 'Prince', 'David Bowie', 'Elton John', 'Stevie Wonder', 'A'],
            ['How many lines are on a standard musical staff?', '4', '5', '6', '7', 'B'],
            ['Which K-pop group is known for hits like "Dynamite" and "Butter"?', 'BLACKPINK', 'BTS', 'EXO', 'TWICE', 'B'],
            ['Which musical term describes a fast tempo?', 'Adagio', 'Andante', 'Allegro', 'Largo', 'C'],
        ]);

        $this->seedCategory('Space', [
            ['What is the closest planet to the Sun?', 'Venus', 'Earth', 'Mercury', 'Mars', 'C'],
            ['Who was the first human to walk on the Moon?', 'Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn', 'B'],
            ['What is the name of our galaxy?', 'Andromeda', 'Milky Way', 'Triangulum', 'Whirlpool', 'B'],
            ['Which planet is known for its prominent ring system?', 'Jupiter', 'Uranus', 'Saturn', 'Neptune', 'C'],
            ['What is the term for a star that explodes at the end of its life?', 'Black hole', 'Supernova', 'Nebula', 'Pulsar', 'B'],
            ['About how long does it take Earth to orbit the Sun?', '24 hours', '30 days', '365.25 days', '12 years', 'C'],
            ['Which was the first artificial satellite launched into space?', 'Sputnik 1', 'Apollo 11', 'Voyager 1', 'Explorer 1', 'A'],
            ['What is the largest planet in our solar system?', 'Saturn', 'Jupiter', 'Neptune', 'Uranus', 'B'],
            ['What do you call a large cloud of gas and dust in space where stars form?', 'Galaxy', 'Nebula', 'Asteroid belt', 'Comet', 'B'],
            ['Which space agency led the James Webb Space Telescope mission?', 'ESA', 'NASA', 'Roscosmos', 'JAXA', 'B'],
            ['What force keeps planets in orbit around the Sun?', 'Magnetism', 'Gravity', 'Friction', 'Inertia', 'B'],
            ['Which planet is known as the "Red Planet"?', 'Venus', 'Mars', 'Jupiter', 'Mercury', 'B'],
            ['What is the term for the point in a planet\'s orbit closest to the Sun?', 'Apogee', 'Perigee', 'Perihelion', 'Aphelion', 'C'],
            ['Which spacecraft carried the first humans to land on the Moon in 1969?', 'Apollo 11', 'Apollo 13', 'Gemini 8', 'Mercury-Atlas 6', 'A'],
            ['What is a black hole?', 'A dead star with gravity so strong nothing can escape', 'An empty region of space', 'A type of nebula', 'A collapsed planet', 'A'],
            ['As of recent counts, which planet has the most confirmed moons?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'B'],
            ['What is the name of the reusable rocket company founded by Elon Musk?', 'Blue Origin', 'Virgin Galactic', 'SpaceX', 'Rocket Lab', 'C'],
            ['Which star is at the center of our solar system?', 'Proxima Centauri', 'The Sun', 'Sirius', 'Alpha Centauri', 'B'],
            ['What term describes a rocky object orbiting the Sun that is too small to be classified as a planet?', 'Comet', 'Asteroid', 'Meteoroid', 'Moon', 'B'],
            ['Which planet has an axial tilt of about 98 degrees, causing it to spin on its side?', 'Neptune', 'Uranus', 'Saturn', 'Venus', 'B'],
            ['Which NASA rover landed on Mars in 2021?', 'Curiosity', 'Opportunity', 'Perseverance', 'Spirit', 'C'],
            ['Which galaxy is on a collision course with the Milky Way, billions of years from now?', 'Triangulum', 'Andromeda', 'Whirlpool', 'Sombrero', 'B'],
            ['What do astronomers call a group of stars forming a recognizable pattern?', 'Galaxy', 'Constellation', 'Cluster', 'Nebula', 'B'],
            ['Which planet is closest in size to Earth?', 'Mars', 'Venus', 'Mercury', 'Neptune', 'B'],
            ['What forms around a comet as it nears the Sun and heats up?', 'A corona', 'A coma and tail', 'A halo', 'An aurora', 'B'],
            ['Which country\'s space program launched the first artificial satellite into orbit?', 'United States', 'Soviet Union', 'China', 'Japan', 'B'],
            ['What is it called when one celestial body passes in front of and blocks another, such as the Moon blocking the Sun?', 'Eclipse', 'Transit', 'Occultation', 'Conjunction', 'A'],
            ['How many planets are recognized in our solar system today?', '7', '8', '9', '10', 'B'],
            ['What is the name of the crewed space station currently orbiting Earth with a rotating international crew?', 'Mir', 'Skylab', 'International Space Station', 'Tiangong', 'C'],
            ['Which astronomer proposed that Earth and the planets revolve around the Sun?', 'Galileo Galilei', 'Nicolaus Copernicus', 'Johannes Kepler', 'Isaac Newton', 'B'],
        ]);

        $this->seedCategory('Sports', [
            ['How many players are on a standard soccer (football) team on the field at once?', '9', '10', '11', '12', 'C'],
            ['In tennis, what is a score of zero called?', 'Nil', 'Love', 'Deuce', 'Ace', 'B'],
            ['How many rings are on the Olympic flag?', '4', '5', '6', '7', 'B'],
            ['Which country won the first-ever FIFA World Cup in 1930?', 'Brazil', 'Uruguay', 'Argentina', 'Italy', 'B'],
            ['In basketball, how many points is a standard field goal worth from inside the three-point line?', '1', '2', '3', '4', 'B'],
            ['What sport is played at Wimbledon?', 'Golf', 'Tennis', 'Cricket', 'Rugby', 'B'],
            ['How many players are on a standard basketball team on the court at once?', '4', '5', '6', '7', 'B'],
            ['In golf, what term describes completing a hole one stroke under par?', 'Bogey', 'Eagle', 'Birdie', 'Albatross', 'C'],
            ['Which country hosted the 2016 Summer Olympics?', 'China', 'United Kingdom', 'Brazil', 'Japan', 'C'],
            ['The Summer Olympic Games are scheduled to be held how often?', 'Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years', 'C'],
            ['How many players are on a standard baseball team on the field at once?', '8', '9', '10', '11', 'B'],
            ['In which sport would you perform a "slam dunk"?', 'Volleyball', 'Basketball', 'Handball', 'Football', 'B'],
            ['How often are the Winter Olympic Games held?', 'Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years', 'C'],
            ['Which country is widely credited with inventing the sport of golf?', 'England', 'Scotland', 'Ireland', 'Wales', 'B'],
            ['In American football, how many points is a touchdown worth?', '3', '6', '7', '8', 'B'],
            ['What is the term for finishing a hole three strokes under par in golf?', 'Eagle', 'Birdie', 'Albatross', 'Bogey', 'C'],
            ['How many holes are played in a standard round of golf?', '9', '12', '18', '24', 'C'],
            ['Which sport is nicknamed "the beautiful game"?', 'Basketball', 'Soccer', 'Rugby', 'Cricket', 'B'],
            ['How many rounds are in a standard professional championship boxing match?', '8', '10', '12', '15', 'C'],
            ['What is the maximum possible score in ten-pin bowling?', '200', '250', '300', '350', 'C'],
            ['Which country has won the most FIFA World Cup titles?', 'Germany', 'Argentina', 'Italy', 'Brazil', 'D'],
            ['In cricket, how many players are on each team?', '9', '10', '11', '12', 'C'],
            ['What is the term for a tied score in soccer?', 'Draw', 'Push', 'Stalemate', 'Even', 'A'],
            ['Which racket sport is played with a shuttlecock?', 'Tennis', 'Squash', 'Badminton', 'Table tennis', 'C'],
            ['How many periods are in a standard ice hockey game?', '2', '3', '4', '5', 'B'],
            ['In which sport would you find a "pommel horse" event?', 'Diving', 'Gymnastics', 'Figure skating', 'Wrestling', 'B'],
            ['Which country hosts the Tour de France, the world\'s most famous cycling race?', 'Spain', 'Italy', 'France', 'Belgium', 'C'],
            ['In tennis, how many sets must a player typically win to take a men\'s Grand Slam match?', '2 of 3', '3 of 5', '4 of 7', 'Best of 1', 'B'],
            ['Which sport features events like the 100m dash, long jump, and javelin throw?', 'Gymnastics', 'Track and field', 'Swimming', 'Cycling', 'B'],
            ['Which sport uses terms like "love," "deuce," and "ace"?', 'Badminton', 'Tennis', 'Squash', 'Table tennis', 'B'],
        ]);

        $this->seedCategory('Geography', [
            ['What is the largest country in the world by land area?', 'Canada', 'China', 'United States', 'Russia', 'D'],
            ['Which African river is the longest river in Africa?', 'Congo River', 'Niger River', 'Nile River', 'Zambezi River', 'C'],
            ['Which desert is the largest hot desert in the world?', 'Gobi Desert', 'Kalahari Desert', 'Sahara Desert', 'Arabian Desert', 'C'],
            ['What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 'C'],
            ['Which mountain is the tallest in the world above sea level?', 'K2', 'Mount Kilimanjaro', 'Mount Everest', 'Denali', 'C'],
            ['How many continents are there?', '5', '6', '7', '8', 'C'],
            ['Which country is transcontinental, spanning both Europe and Asia?', 'Turkey', 'Egypt', 'Morocco', 'Greece', 'A'],
            ['What is the smallest country in the world by area?', 'Monaco', 'San Marino', 'Vatican City', 'Liechtenstein', 'C'],
            ['Which river flows through Egypt?', 'Amazon', 'Nile', 'Congo', 'Niger', 'B'],
            ['What is the capital of Japan?', 'Osaka', 'Kyoto', 'Tokyo', 'Yokohama', 'C'],
            ['What is traditionally cited as the longest river in the world?', 'Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River', 'B'],
            ['Which country has the most natural lakes in the world?', 'Canada', 'Russia', 'United States', 'Finland', 'A'],
            ['What is the capital city of France?', 'Marseille', 'Lyon', 'Paris', 'Nice', 'C'],
            ['Which continent is the largest by land area?', 'Africa', 'Asia', 'North America', 'Europe', 'B'],
            ['What is the smallest continent by land area?', 'Europe', 'Antarctica', 'Australia', 'South America', 'C'],
            ['Which country is known as the "Land of the Rising Sun"?', 'China', 'South Korea', 'Japan', 'Thailand', 'C'],
            ['What is the capital of Canada?', 'Toronto', 'Vancouver', 'Montreal', 'Ottawa', 'D'],
            ['Which mountain range is traditionally considered to separate Europe and Asia?', 'Alps', 'Andes', 'Ural Mountains', 'Himalayas', 'C'],
            ['What is the largest island in the world, excluding continental landmasses?', 'Madagascar', 'Greenland', 'Borneo', 'New Guinea', 'B'],
            ['Which African country was formerly known as Abyssinia?', 'Kenya', 'Ethiopia', 'Sudan', 'Somalia', 'B'],
            ['What is the capital of Egypt?', 'Alexandria', 'Cairo', 'Giza', 'Luxor', 'B'],
            ['Which US state is nicknamed the "Sunshine State"?', 'California', 'Florida', 'Arizona', 'Texas', 'B'],
            ['What is the name of the imaginary line at 0 degrees latitude?', 'Prime Meridian', 'Tropic of Cancer', 'Equator', 'Arctic Circle', 'C'],
            ['Which country has the largest population in the world as of the 2020s?', 'China', 'India', 'United States', 'Indonesia', 'B'],
            ['What is the capital of Brazil?', 'Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador', 'C'],
            ['Which sea lies between Europe and Africa, connecting to the Atlantic via the Strait of Gibraltar?', 'Adriatic Sea', 'Mediterranean Sea', 'Black Sea', 'Aegean Sea', 'B'],
            ['Which country, made up of over 17,000 islands, is the world\'s largest archipelago?', 'Philippines', 'Indonesia', 'Japan', 'Malaysia', 'B'],
            ['What is the driest inhabited continent on Earth?', 'Africa', 'Australia', 'Asia', 'South America', 'B'],
            ['Which European country is famously shaped like a boot?', 'Spain', 'Greece', 'Italy', 'Portugal', 'C'],
            ['What was the name of the wall that historically divided East and West Germany\'s capital city?', 'The Great Wall', 'The Berlin Wall', 'The Iron Curtain', 'Hadrian\'s Wall', 'B'],
        ]);

        $this->seedCategory('Video Games', [
            ['Which company created the video game franchise "Super Mario"?', 'Sega', 'Nintendo', 'Sony', 'Capcom', 'B'],
            ['Which video game is widely cited as the best-selling video game of all time?', 'Tetris', 'Minecraft', 'Grand Theft Auto V', 'Wii Sports', 'B'],
            ['Which video game franchise features a green-clad hero named Link?', 'Final Fantasy', 'The Legend of Zelda', 'Kingdom Hearts', 'Metroid', 'B'],
            ['Which company developed the "PlayStation" console?', 'Microsoft', 'Nintendo', 'Sony', 'Atari', 'C'],
            ['Which puzzle video game involves fitting falling blocks together?', 'Pac-Man', 'Tetris', 'Snake', 'Space Invaders', 'B'],
            ['In "Stardew Valley," what do you inherit from your grandfather at the start of the game?', 'A farm', 'A shop', 'A boat', 'A mine', 'A'],
            ['In "Subnautica," what is the name of the spaceship that crashes at the start of the game?', 'The Odyssey', 'The Aurora', 'The Nautilus', 'The Voyager', 'B'],
            ['Which video game franchise is set primarily in the fictional city of Los Santos?', 'Saints Row', 'Watch Dogs', 'Grand Theft Auto', 'Sleeping Dogs', 'C'],
            ['In which video game series would you find the character "Master Chief"?', 'Gears of War', 'Call of Duty', 'Destiny', 'Halo', 'D'],
            ['Which blue hedgehog is the mascot of a long-running Sega video game franchise?', 'Crash Bandicoot', 'Sonic', 'Rayman', 'Spyro', 'B'],
            ['In Minecraft, what material — along with sticks — is needed to craft a diamond pickaxe?', 'Diamonds', 'Iron', 'Gold', 'Emeralds', 'A'],
            ['What is the name of the hostile mob in Minecraft that explodes near players?', 'Zombie', 'Creeper', 'Skeleton', 'Enderman', 'B'],
            ['In Minecraft, which dimension do you reach through an obsidian portal?', 'The End', 'The Nether', 'The Overworld', 'The Aether', 'B'],
            ['What is the most durable tool material in Minecraft before Netherite is introduced?', 'Iron', 'Gold', 'Diamond', 'Stone', 'C'],
            ['In Minecraft, which mob drops ender pearls when defeated?', 'Enderman', 'Zombie', 'Blaze', 'Ghast', 'A'],
            ['In "Subnautica," what is the designation of the ocean planet the game takes place on?', '4546B', 'Planet X', 'Aurora Prime', 'Kharaa', 'A'],
            ['In "Subnautica," which tool is primarily used to construct bases underwater?', 'Habitat Builder', 'Construction Gun', 'Fabricator', 'Mobile Vehicle Bay', 'A'],
            ['What is the name of the deadly pathogen central to "Subnautica\'s" story?', 'The Blight', 'Kharaa Bacterium', 'The Rot', 'Aurora Syndrome', 'B'],
            ['Which vehicle in "Subnautica" is typically the first submarine players construct?', 'Cyclops', 'Seamoth', 'Prawn Suit', 'Seaglide', 'B'],
            ['In "Subnautica," which large submarine can carry other vehicles inside it?', 'Seamoth', 'Prawn Suit', 'Cyclops', 'Neptune', 'C'],
            ['In "Mario Kart," which item grants brief invincibility and a speed boost?', 'Mushroom', 'Star', 'Bullet Bill', 'Lightning', 'B'],
            ['Which "Mario Kart" item temporarily shrinks every opponent on the track?', 'Blooper', 'Lightning Bolt', 'Banana Peel', 'Bob-omb', 'B'],
            ['Which "Mario Kart" track is famous for its rainbow-colored road with no guardrails?', 'Bowser\'s Castle', 'Rainbow Road', 'Star Cup', 'Sky Garden', 'B'],
            ['In "Mario Kart," which heavyweight character is Mario\'s longtime rival?', 'Luigi', 'Bowser', 'Toad', 'Yoshi', 'B'],
            ['Which "Mario Kart" item trails behind a kart and can block or hit incoming attacks?', 'Green Shell', 'Banana Peel', 'Red Shell', 'Star', 'B'],
            ['In "Stardew Valley," which season is best for planting parsnips?', 'Spring', 'Summer', 'Fall', 'Winter', 'A'],
            ['What is the name of the town where "Stardew Valley" takes place?', 'Pelican Town', 'Zuzu City', 'Stardew Hollow', 'Cindersap Village', 'A'],
            ['In "Stardew Valley," which building can players restore to unlock bundles and rewards?', 'The Saloon', 'The Community Center', 'JojaMart', 'The Museum', 'B'],
            ['Which corporation threatens to buy out and replace the Community Center in "Stardew Valley"?', 'JojaMart', 'MegaCorp', 'FarmCo', 'ValleyMart', 'A'],
            ['In "Stardew Valley," which tool is used to water your crops?', 'Hoe', 'Watering Can', 'Scythe', 'Pickaxe', 'B'],
        ]);

        $this->seedCategory('Game Night', [
            ['In chess, how many squares are on the board?', '32', '48', '64', '100', 'C'],
            ['What is the objective of the card game "Uno"?', 'Collect all four suits', 'Be the first to get rid of all your cards', 'Build the highest score', 'Trade cards with opponents', 'B'],
            ['In Monopoly, how much money do you collect when you pass "Go"?', '$100', '$200', '$300', '$400', 'B'],
            ['How many pieces does each player start with in a game of chess?', '12', '14', '16', '18', 'C'],
            ['In standard Scrabble, how many points is each "Q" or "Z" tile worth?', '5', '8', '10', '12', 'C'],
            ['In the board game "Clue" (Cluedo), how many weapons are there to choose from?', '5', '6', '7', '8', 'B'],
            ['What is the maximum number of players in the standard base version of "Catan"?', '3', '4', '5', '6', 'B'],
            ['In poker, what is the highest-ranking standard hand?', 'Four of a Kind', 'Full House', 'Royal Flush', 'Straight Flush', 'C'],
            ['In "Yahtzee," how many dice are used?', '4', '5', '6', '7', 'B'],
            ['In Checkers (Draughts), how many pieces does each player start with?', '10', '12', '14', '16', 'B'],
            ['In "Uno," what happens when a "Wild Draw Four" card is played?', 'Next player draws 4 and is skipped', 'All players draw 4', 'The game ends', 'Colors reset', 'A'],
            ['How many tiles are in a standard set of Scrabble?', '100', '98', '102', '104', 'A'],
            ['In Monopoly, what does "Free Parking" typically do under common house rules?', 'Sends you to jail', 'Awards you money left in a pool', 'Skips your turn', 'Cancels your rent', 'B'],
            ['What is the objective of the game "Jenga"?', 'Build the tallest tower', 'Remove blocks without toppling the tower', 'Stack blocks by color', 'Roll dice to win blocks', 'B'],
            ['In chess, which piece is the only one that can jump over other pieces?', 'Bishop', 'Rook', 'Knight', 'Queen', 'C'],
            ['How many cards are in a standard deck of playing cards, excluding jokers?', '48', '50', '52', '54', 'C'],
            ['In the classic version of "Battleship," how many ships does each player place?', '3', '4', '5', '6', 'C'],
            ['What is it called when a chess player traps the opponent\'s king with no legal moves left?', 'Stalemate', 'Checkmate', 'Check', 'Fork', 'B'],
            ['In "Trivial Pursuit," what shape are the pieces used to track categories answered?', 'Squares', 'Wedges', 'Circles', 'Triangles', 'B'],
            ['How many dice are used in a standard game of "Farkle"?', '5', '6', '7', '8', 'B'],
            ['What is the main goal of the board game "Risk"?', 'Collect the most cards', 'Conquer all the territories on the board', 'Reach a set number of points', 'Trade resources', 'B'],
            ['Which classic game uses a "Pop-o-matic" dice bubble to race pegs around the board?', 'Sorry!', 'Trouble', 'Parcheesi', 'Aggravation', 'B'],
            ['In "Candy Land," how do players move around the board?', 'Rolling dice', 'Drawing colored cards', 'Spinning a wheel', 'Flipping coins', 'B'],
            ['How many pegs does each player control in a standard game of "Sorry!"?', '3', '4', '5', '6', 'B'],
            ['In "Twister," what determines the moves players must make?', 'A spinner', 'Dice', 'Cards', 'A timer', 'A'],
            ['What is the maximum number of players in a standard game of "Clue" (Cluedo)?', '4', '5', '6', '8', 'C'],
            ['In backgammon, what determines how many spaces a player can move?', 'Cards', 'Dice', 'A spinner', 'A coin flip', 'B'],
            ['What is the name of the fast-paced card game where players slap the pile when doubles appear?', 'War', 'Egyptian Ratscrew', 'Speed', 'Spit', 'B'],
            ['In "Pictionary," how must players help their team guess the word?', 'Act it out', 'Draw it', 'Describe it with one word', 'Hum it', 'B'],
            ['How many pawn colors are used in a standard game of "Sorry!"?', '2', '3', '4', '6', 'C'],
        ]);
    }

    /**
     * Insert a category's worth of questions.
     * Each row is [question_text, option_a, option_b, option_c, option_d, correct_option].
     */
    private function seedCategory(string $categoryName, array $rows): void
    {
        $categoryId = DB::table('categories')->where('name', $categoryName)->value('id');

        DB::table('questions')->insert(array_map(
            fn (array $row) => [
                'question_text' => $row[0],
                'option_a' => $row[1],
                'option_b' => $row[2],
                'option_c' => $row[3],
                'option_d' => $row[4],
                'correct_option' => $row[5],
                'category_id' => $categoryId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            $rows
        ));
    }
}
